name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install CargoMake
      run: cargo install --debug cargo-make
    - name: Run CI Build
      run: cargo make ci-flow
